version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - .:/app # Kod o'zgarsa, qayta yuklamaslik uchun
      - static_volume:/app/staticfiles # Static fayllar joyi
      - media_volume:/app/media # Media fayllar joyi
      - db_data:/app/db_data # SQLite bazasi uchun papka
    expose:
      - 8000

  # 2. Nginx (Veb server)
  nginx:
    image: nginx:1.25-alpine
    ports:
      - '80:80' # Internetga 80-portni ochamiz
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Biz yozgan config
      - static_volume:/app/staticfiles # Django yig'gan staticlarni o'qiydi
      - media_volume:/app/media # Yuklangan rasmlarni o'qiydi
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  db_data:
